### ISSUE TITLE
Perhaps use doubles instead of floats? (for Sliders at least)

### ISSUE THREAD

**Issue by JobLeonard** [fjenett/Guido#7]
Hey,

Just discovered this library, looks really nice! So far I've been basically manually crafting my own UI using Processing, [example here](https://www.youtube.com/watch?v=4BnEIZHWJNY), and it looks very similar, but you have much cleaner code so I'm looking forward to using the library.

Anyway, my experience with sliders is that floating point are just a little bit too imprecise if I want to convert the number to integer values.

Since UI elements aren't going to be involved in heavy computation, why not use doubles instead of floats? In JavaScript they will be anyway, so I suspect it would also make the behaviour more consistent between Java and JavaScript modes.

**Comment by fjenett** [comment]
In the examples? ... sure, you could just change that easily if you need the extra precision. The value variable is not hardcoded into the library but your own code. As the examples need no finer precision i think i'm leaving it as is so it is more familiar with the Processing community.
But thanks for pointing that out ... i think i might add a comment to note it.

**Comment by JobLeonard** [comment]
Ah, right, I see now. And the Processing functions don't handle doubles very well so that would make the example harder to copy/paste for simple use-cases. Makes sense. 

I think it's a good idea to warn that JavaScript uses doubles for everything though, and that this could make the library act differently - probably will save at least one person some bug hunting later on.

PS: You're quick to respond!

**Comment by fjenett** [comment]
Yup, Processing is all float ...

I don't need the warning as the library itself is not acting different, it's only your own code. That warning would then need to go to Processing.js / Processing code bases, not here ... no?

Quick? .. only sometimes. :)

**Comment by JobLeonard** [comment]
Fair enough, although I wonder if such a warning is currently present in any of the tutorials.
